names:
- no_seatbelt
- mobile
- inattentive
- seatbelt
- drowsiness
- drinking
nc: 6
test: ../../incremental_dataset/round_5/test/images
train: ../../incremental_dataset/round_5/train/images
val: ../../incremental_dataset/round_5/val/images
